
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092      
      
  data:                     
    mongodb:
      host: ms-creature-write-db
      port: 27017
       
    redis:
      host: ms-creature-redis-db
      port: 6379 
 
  r2dbc:
    host: ms-creature-read-db
    port: 5432
      
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://oauth2-server:9000 
       
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
                       
# Basic data for /actuator/info
info:
  app:
    profile: prod 
          