
name:  nano-bestiary-prod

services:

  ms-creature-write-db:
    image: mongo:8.0.3-noble
    container_name: ms-creature-write-db
    environment:
      MONGO_INITDB_DATABASE: mongo-write-db
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS_WRITE}
    networks:
      - nano-bestiary-net
    ports:
      - 27017:27017 
    restart: on-failure:3
    healthcheck: &healthcheck-write-db
      test: "echo 'db.runCommand(\"ping\").ok'"
      interval: 5s
      timeout: 5s
      retries: 3

  ms-creature-read-db:
    image: postgres:17.1-alpine
    container_name: ms-creature-read-db
    environment:
       POSTGRES_PASSWORD: ${SQLDB_PASS}
       POSTGRES_USER: root
       POSTGRES_DB: creatureReadDb
    volumes:
      - ./databases/ms-creature/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nano-bestiary-net
    ports:
      - 5432:5432
    restart: on-failure:3
    healthcheck: &healthcheck-read-db
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
       
  ms-creature-redis-db:
    image: redis:7.4-alpine
    container_name: ms-creature-redis-db
    networks:
      - nano-bestiary-net
    ports:
      - 6379:6379
    restart: on-failure:3
    healthcheck: &healthcheck-redis-db
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      
  ms-area-write-db:
    image: mongo:8.0.3-noble
    container_name: ms-area-write-db
    environment:
      MONGO_INITDB_DATABASE: mongo-write-db
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS_WRITE}    
    networks:
      - nano-bestiary-net
    ports:
      - 27018:27017
    restart: on-failure:3
    healthcheck: *healthcheck-write-db
  
  ms-area-read-db:
    image: postgres:17.1-alpine
    container_name: ms-area-read-db
    environment:
       POSTGRES_PASSWORD: ${SQLDB_PASS}
       POSTGRES_USER: root
       POSTGRES_DB: areaReadDb
    volumes:
      - ./databases/ms-area/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
     - nano-bestiary-net
    ports:
      - 5433:5432
    restart: on-failure:3
    healthcheck: *healthcheck-read-db 	
      
  ms-area-redis-db:
    image: redis:7.4-alpine
    container_name: ms-area-redis-db
    networks:
      - nano-bestiary-net
    ports:
      - 6380:6379
    restart: on-failure:3
    healthcheck: *healthcheck-redis-db
      
  kafka:
    image: bitnami/kafka:3.8
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=nige-jozu-kafka
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes    
      - KAFKA_AUTO_OFFSET_RESET=earliest       
      - BITNAMI_DEBUG=true        
#    volumes:
#      - kafka_persistent:/var/lib/kafka
    networks:
      - nano-bestiary-net
    ports:
      - 9092:9092
      - 9093:9093
    restart: on-failure:3
    healthcheck:
      test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9092; exit $$?;'"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: nige-jozu-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - nano-bestiary-net
    ports:
      - 8081:8080
    restart: on-failure:3    
    depends_on:
      kafka:
        condition: service_healthy

  kafka-data:
    build: ./databases/kafka-data
    container_name: kafka-data
    volumes:
      - ./databases/kafka-data/init-kafka-data.sh:/init-kafka-data.sh
    command: ["/bin/bash", "/init-kafka-data.sh", "9092"]
    networks:
      - nano-bestiary-net
    depends_on:
      kafka:
        condition: service_healthy
    
  eureka-server:
    container_name: eureka-server
    build:
      dockerfile_inline: |
        FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
        WORKDIR /app
        COPY ./pom.xml ./
        COPY ./eureka-server/pom.xml ./eureka-server/
        COPY ./src ./src
        COPY ./eureka-server/src ./eureka-server/src
        RUN cd ./eureka-server && mvn clean package -DskipTests
        FROM eclipse-temurin:21-jre-alpine
        WORKDIR /app
        COPY --from=builder /app/eureka-server/target/*.jar ./app.jar
        ENTRYPOINT [ "java", "-jar", "./app.jar" ] 
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - nano-bestiary-net
    ports:
      - 8761:8761
    restart: on-failure:3
    healthcheck:
      test: "${EUREKA_HEALTHCHECK_TEST:-wget --no-verbose --tries=1 --spider http://eureka-server:8761/actuator/health || exit 1}"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  
  api-gateway:
    container_name: api-gateway
    build:
      dockerfile_inline: |
        FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
        WORKDIR /app
        COPY ./pom.xml ./
        COPY ./api-gateway/pom.xml ./api-gateway/
        COPY ./src ./src
        COPY ./api-gateway/src ./api-gateway/src
        RUN cd ./api-gateway && mvn clean package -DskipTests
        FROM eclipse-temurin:21-jre-alpine
        WORKDIR /app
        COPY --from=builder /app/api-gateway/target/*.jar ./app.jar
        ENTRYPOINT [ "java", "-jar", "./app.jar" ] 
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - nano-bestiary-net
    ports:
      - 8080:8080
    restart: on-failure:3
    healthcheck:
      test: "${API_GATEWAY_HEALTHCHECK_TEST:-wget --no-verbose --tries=1 --spider http://api-gateway:8080/actuator/health || exit 1}"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    depends_on:
      eureka-server:
        condition: service_healthy
    
  oauth2-server:
    container_name: oauth2-server
    build:
      dockerfile_inline: |
        FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
        WORKDIR /app
        COPY ./pom.xml ./
        COPY ./oauth2-server/pom.xml ./oauth2-server/
        COPY ./src ./src
        COPY ./oauth2-server/src ./oauth2-server/src
        RUN cd ./oauth2-server && mvn clean package -DskipTests
        FROM eclipse-temurin:21-jre-alpine
        WORKDIR /app
        COPY --from=builder /app/oauth2-server/target/*.jar ./app.jar
        ENTRYPOINT [ "java", "-jar", "./app.jar" ] 
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - nano-bestiary-net
    ports:
      - 9000:9000
    restart: on-failure:3
           
  ms-area:
    #container_name: ms-area
    build:
      dockerfile_inline: |
        FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
        WORKDIR /app
        COPY ./pom.xml ./
        COPY ./ms-area/pom.xml ./ms-area/
        COPY ./src ./src
        COPY ./ms-area/src ./ms-area/src
        RUN cd ./ms-area && mvn clean package -DskipTests
        FROM eclipse-temurin:21-jre-alpine
        WORKDIR /app
        COPY --from=builder /app/ms-area/target/*.jar ./app.jar
        ENTRYPOINT [ "java", "-jar", "./app.jar" ] 
    deploy:
      replicas: ${MS_AREA_REPLICAS:-2}
    env_file: ./.env   
    environment:
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - nano-bestiary-net
    restart: on-failure:3
    depends_on:
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      ms-area-read-db:
        condition: service_healthy
      ms-area-write-db:
        condition: service_healthy
      ms-area-redis-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
 
  ms-creature:
    #container_name: ms-creature
    build:
      dockerfile_inline: |
        FROM maven:3.9.6-eclipse-temurin-21-alpine AS builder
        WORKDIR /app
        COPY ./pom.xml ./
        COPY ./ms-creature/pom.xml ./ms-creature/
        COPY ./src ./src
        COPY ./ms-creature/src ./ms-creature/src
        RUN cd ./ms-creature && mvn clean package -DskipTests
        FROM eclipse-temurin:21-jre-alpine
        WORKDIR /app
        COPY --from=builder /app/ms-creature/target/*.jar ./app.jar
        ENTRYPOINT [ "java", "-jar", "./app.jar" ] 
    deploy:
      replicas: ${MS_CREATURE_REPLICAS:-2}
    env_file: ./.env   
    environment: 
      SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE:-prod}
    networks:
      - nano-bestiary-net
    restart: on-failure:3
    depends_on:
      eureka-server:
        condition: service_healthy
      api-gateway:
        condition: service_healthy
      ms-creature-read-db:
        condition: service_healthy
      ms-creature-write-db:
        condition: service_healthy
      ms-creature-redis-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
              
   
networks:
  nano-bestiary-net:
    name: nano-bestiary-net
    ipam:
      config:
        - subnet: 172.23.33.0/24
          gateway: 172.23.33.1
          
  