apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: plaintext
    - port: 9093
      targetPort: 9093
      name: controller
    - port: 29092
      targetPort: 29092
      name: external
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_KRAFT_CLUSTER_ID: "nige-jozu-kafka"
  KAFKA_CFG_BROKER_ID: "1"
  KAFKA_CFG_NODE_ID: "1"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092"
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,EXTERNAL://kafka:29092"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_AUTO_OFFSET_RESET: "earliest"
  BITNAMI_DEBUG: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.8
          envFrom:
            - configMapRef:
                name: kafka-config            
          ports:
            - containerPort: 9092
            - containerPort: 9093
            - containerPort: 29092
            