apiVersion: v1
kind: Service
metadata:
  name: ms-creature-write-db
spec:
  selector:
    app: ms-creature-write-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-creature-write-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-creature-write-db
  template:
    metadata:
      labels:
        app: ms-creature-write-db
    spec:
      containers:
      - name: ms-creature-write-db
        image: mongo:8.0.3-noble
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: mongo-write-db
        - name: MONGO_INITDB_ROOT_USERNAME
          value: sa
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb-password-write
---
apiVersion: v1
kind: Service
metadata:
  name: ms-creature-read-db
spec:
  selector:
    app: ms-creature-read-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-creature-read-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-creature-read-db
  template:
    metadata:
      labels:
        app: ms-creature-read-db
    spec:
      containers:
        - name: ms-creature-read-db
          image: postgres:17.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqldb-secret
                  key: SQLDB_PASS
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_DB
              value: creatureReadDb
          volumeMounts:
            - name: ms-creature-read-db-init-sql-vol
              mountPath: /docker-entrypoint-initdb.d
          ports:
            - containerPort: 5432
      volumes:
        - name: ms-creature-read-db-init-sql-vol
          configMap:
            name: ms-creature-read-db-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: ms-creature-redis-db
spec:
  selector:
    app: ms-creature-redis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-creature-redis-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-creature-redis-db
  template:
    metadata:
      labels:
        app: ms-creature-redis-db
    spec:
      containers:
        - name: ms-creature-redis-db
          image: redis:7.4-alpine
          ports:
            - containerPort: 6379
---
