apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
data:
  mongodb-password-write: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-area-read-db-init-sql
data:
  init.sql: |
    DROP DATABASE IF EXISTS areaReadDb;    
    CREATE DATABASE areaReadDb;    
    DROP TABLE IF EXISTS areas;    
    CREATE TABLE areas(
      area_id uuid NOT NULL,
      area_name varchar(255) NOT NULL UNIQUE,
      CONSTRAINT areas_PK PRIMARY KEY(area_id));
---     
apiVersion: v1
kind: Secret
metadata:
  name: sqldb-secret
type: Opaque
data:
  SQLDB_PASS: YWJjZGU=
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-creature-read-db-init-sql
data:
  init.sql: |
    DROP DATABASE IF EXISTS creatureReadDb;    
    CREATE DATABASE creatureReadDb;    
    DROP TABLE IF EXISTS creatures;    
    CREATE TABLE creatures(
      creature_id uuid NOT NULL,
      creature_name VARCHAR(255) NOT NULL UNIQUE,
      creature_description VARCHAR(255) NOT NULL,
      area_id uuid NOT NULL,
      CONSTRAINT creatures_PK PRIMARY KEY(creature_id)
      );      
---