
spring: 
  kafka:
    producer:
      bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092 

properties:
  authorization:
    server:
      issuer: http://oauth2-server:${server.port}
            
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    